
name: 'dev'
version: '1.0.0'
config-version: 2

profile: 'stack'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  dev:
      staging:
        materialized: view
        schema: staging
      transformation:
        materialized: view
        schema: transformation
      warehouse:
        materialized: table
        schema: warehouse
      qa:
        materialized: view
        schema: qa
      utils:
        materialized: view
        schema: logs
