version: 2

models:

  - name: dim_badges
    description: badges reference table
    columns:
      - name: badges_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: dim_posts
    description: post reference table
    columns:
      - name: post_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: dim_topics
    description: topic reference table
    columns:
      - name: topic_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: dim_users
    description: user reference table
    columns:
      - name: user_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: fact
    description: badges reference table
    columns:
      - name: post_pk
        description: >
          primary key
        tests:
          - unique
          - not_null
