version: 2

models:

  - name: dim_badges
    description: badges reference table
    columns:
      - name: badges_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: dim_posts
    description: post reference table
    columns:
      - name: post_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: dim_topics
    description: topic reference table
    columns:
      - name: topic_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: dim_users
    description: user reference table
    columns:
      - name: user_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: fact
    description: badges reference table
    columns:
      - name: post_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: dim_topic_sets
    description: table of unique topic sets
    columns:
      - name: topic_set_pk
        description: >
          primary key
        tests:
          - unique
          - not_null

  - name: bridge_topics
    description: bridge table between topic refernce table and fact table
    columns:
      - name: topic_set_fk
        description: >
          foreign key
        tests:
          - not_null
      - name: topic_fk
        description: >
          foreign key
        tests:
          - not_null
